### ISSUE TITLE
fontsDir is not returning the good path

### ISSUE THREAD

**Issue by vivivers** [battlesnake/gulp-google-webfonts#13]
Hi,

I've put my .list in my app dir and I tried to output the font in my public dir. Since the fontDir path is relative to .list I've put something like this '../../../public/dir/fonts/' but it didn't work. I can go two steps back '../../public/dir/fonts/' but not three, I can go three steps back only if I remove some folders like this '../../../public/'.

Thanks!

**Comment by battlesnake** [comment]
Could you provide a test case?

**Comment by battlesnake** [comment]
No test case, closed

**Comment by vivivers** [comment]
Yes sorry, I didn't had the time to do it before. I just created a simple use case here https://github.com/gor0n/Googlewebfonts but it seems to work now. As you can see I try to create a modular gulpfile so maybe I did something wrong.

I'll investigate why it don't work in my project. Unfortunately I can't give access to the project because it's the framework of my company.
