### ISSUE TITLE
Incorrect source paths generated in the CSS when used under Windows.

### ISSUE THREAD

**Issue by allanbjorklund** [battlesnake/gulp-google-webfonts#15]
When using this under Windows, the CSS generated has incorrect source paths.  I tracked the problem down to this function:

function makeFontFace(request) {
    request.name = path.join(options.fontsDir, request.name);
    return template
        .replace(/\$(\w+)/g, function (m, name) { return request[name]; });
}

The error is that 'path' will use the local system's path separator when joining path elements.  The end result is that the web server treats the Windows '\' as an escape character, and returns that there is no such file when trying to access the woff file. (Even when running under Windows.)

The fix is to change the path join statement to the following.

```
request.name = path.posix.join(options.fontsDir, request.name);
```

This will always use the '/' when joining the path elements, and will produce the correct source URL path in the CSS.

**Comment by battlesnake** [comment]
Thanks, done

**Comment by gyretech** [comment]
This change causes the following error:

```
request.name = path.posix.join(options.fontsDir, request.name);
                                          ^
TypeError: Cannot call method 'join' of undefined
```

**Comment by battlesnake** [comment]
You're probably using an old version of Node, `path.posix.join` is in the spec: https://nodejs.org/api/path.html#path_path_posix

**Comment by gyretech** [comment]
Is v5.10.1 old? When I replace "path.posix.join" with "path.join" it works.

**Comment by battlesnake** [comment]
v5.10.1 isn't old, however `path.posix.join` is in the official docs, and `path.join` will break on Windows (a previous PR changed it to the POSIX version).  Since the POSIX version is in the official docs, I'm not going to make any changes here.

Are you definitely loading the built-in `path` module and not some external one?

**Comment by battlesnake** [comment]
It works for me using Node v5.10.1 and NPM v3.8.6 on Arch Linux - what distro are you using?

**Comment by gyretech** [comment]
I am on Windows 10 and it only works when I remove posix.

**Comment by gyretech** [comment]
```
F:\Website\node_modules\gulp-google-webfonts\index.js:209
                request.name = path.posix.join(options.fontsDir, request.name);
                                          ^
TypeError: Cannot call method 'join' of undefined
    at makeFontFace (F:\Website\node_modules\gulp-google-webfonts\index.js:209:31)
    at Array.map (native)
    at generateFontCss (F:\Website\node_modules\gulp-google-webfonts\index.js:204:6)
    at parseCss (F:\Website\node_modules\gulp-google-webfonts\index.js:191:4)
    at fn (F:\Website\node_modules\gulp-google-webfonts\node_modules\async\lib\async.js:638:34)
    at Object._onImmediate (F:\Website\node_modules\gulp-google-webfonts\node_modules\async\lib\async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
Process terminated with code 8.
```

**Comment by battlesnake** [comment]
Ok - I've no idea then.  I'll leave the `.posix.` in, as it's documented and works on Linux and whatever version of Windows the person who originally added it uses.

**Comment by battlesnake** [comment]
Are you definitely loading the built-in `path` module and not some external one?

**Comment by gyretech** [comment]
`"dependencies": {
    "bower": "^1.7.7",
    "del": "^2.2.0",
    "path": "^0.12.7"
  },`

**Comment by battlesnake** [comment]
You're probably not using the built-in if it's listed in `package.json` dependencies.

**Comment by gyretech** [comment]
ok, let me correct that.

**Comment by gyretech** [comment]
Same thing.

**Comment by battlesnake** [comment]
Have you removed the external `path` module completely or just from `package.json`?

**Comment by battlesnake** [comment]
When you've removed it completely, the plugin will work, as you're using the same version of Node as me

**Comment by gyretech** [comment]
I ran `npm uninstall path`.

**Comment by gyretech** [comment]
I also ran `npm -g uninstall path --save`

**Comment by gyretech** [comment]
So I am the only one having this issue?
I am on Windows
`request.name = path.join(options.fontsDir, request.name);` works perfectly fine 

But `request.name = path.posix.join(options.fontsDir, request.name);` gives me an error cannot call method join.

**Comment by battlesnake** [comment]
Apparently.  If you were loading the built-in `path` module and it's up to date then you wouldn't have this problem.  Somewhere, you have a 3rd-party or out-dated version of it which is being loaded.  Do any of the project's parent folders also contain a `node_modules` folder?
