### ISSUE TITLE
Error: Failed to retrieve webfont CSS

### ISSUE THREAD

**Issue by Wtower** [battlesnake/gulp-google-webfonts#16]
When using the tab-delimited format, even with exactly the same example with [README.md](https://github.com/battlesnake/gulp-google-webfonts#fontslist), I get the following output:

```
$ gulpfile.js fonts
[19:03:55] Using gulpfile .../gulpfile.js
[19:03:55] Starting 'fonts'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Failed to retrieve webfont CSS
    at parseCss (.../node_modules/gulp-google-webfonts/index.js:183:17)
    at fn (.../node_modules/gulp-google-webfonts/node_modules/async/lib/async.js:638:34)
    at Immediate._onImmediate (.../node_modules/gulp-google-webfonts/node_modules/async/lib/async.js:554:34)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

Process finished with exit code 1
```

It works properly with Google format. Using gulp-google-webfonts 0.0.12.

**Comment by battlesnake** [comment]
The README.md is auto-generated from the result of executing the examples.  Could you provide more information regarding system configuration, versions, etc

**Comment by Wtower** [comment]
- nvm: v0.30.0
- node.js: v0.12.13
- gulp: v3.9.1
- gulp-google-webfonts: v0.0.12
- OS: Ubuntu 15.10

fonts.list

```
# Tab-delimeted format: NOT working
Oswald  400,700 latin,latin-ext

# Google format: this works OK
Roboto:500,500italic&subset=greek
```

What else is it you would like to know?

**Comment by battlesnake** [comment]
Might sound stupid, but are you definitely using only a single tab to separate the columns - no spaces?  A copy+paste from the README on Github might have the tabs expanded to spaces.

**Comment by Wtower** [comment]
Not stupid at all. I am not sure if github or the IDE changed tabs to spaces, but replacing them with the tab character solved the issue.

Perhaps we should mention something on readme regarding the tab character.

In any case, thanks for the support and congrats for this project. For future reference, one can use gnome's <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>U</kbd>,  <kbd>9</kbd>,  <kbd>enter</kbd>.

**Comment by battlesnake** [comment]
Good to hear.  Some IDEs have stupid default settings such as automatically converting tabs to spaces (called something like "expand tabs", "soft tabs", "Gn00b mode") - might be worth checking for that.  I'll leave the README as-is for now since it already describes the format as `Tab-delimeted format`, and isn't worth an npm version bump just to clarify that more.  I'll try to remember to add more notes regarding it to the next update though.
