### ISSUE TITLE
Feature request:

### ISSUE THREAD

**Issue by JoshuaMorris** [battlesnake/gulp-google-webfonts#17]
I would like to be able to have the output file be sass. can there be an option added to inject your own template?

**Comment by battlesnake** [comment]
You could add it and send a PR, but what do you hope to gain?  Valid CSS is valid SCSS by definition so you could set a `scss` extension on the output then @import it in your SASS

**Comment by marcinant** [comment]
You can also use an option: cssFIlename to save as scss.
