### ISSUE TITLE
Convert woff to other formats?

### ISSUE THREAD

**Issue by jdnichollsc** [battlesnake/gulp-google-webfonts#18]
Hi man,

Is possible to generate other formats? Like:
- eot
- svg
- ttf
- woff2

Regards, Nicholls

**Comment by battlesnake** [comment]
It doesn't generate any files, it just downloads them from Google.  I've only configured it to download WOFF, as virtually every browser around (excluding the nearly-dead IE8) supports WOFF.

**Comment by jdnichollsc** [comment]
Thanks for the info! :dancers:

**Comment by michaelmior** [comment]
@jdnichollsc I recently added a `format` option that will allow you to get the woff2 and ttf versions. Adding support for eot and svg just amounts to finding a user agent string that Google Fonts will serve those types to.

**Comment by gabrielsimoes** [comment]
Hey, you should add this information to the readme.

**Comment by michaelmior** [comment]
@gabrielsimoes The best way to have that happen would probably be for you to write a PR :)

**Comment by battlesnake** [comment]
^^ hooray, someone gets it! :1st_place_medal:
