### ISSUE TITLE
lodash required as project dependency

### ISSUE THREAD

**Issue by marcinant** [battlesnake/gulp-google-webfonts#21]
I use _gulpfile.babel.js_ (ecma script 6) and **gulp fonts** task returns:

```
[04:22:35] Error: Cannot find module 'lodash.restparam'
```

It's fixable by:

```
npm i lodash.restparam --save-dev
```

However I consider this as workaround and it's still a bug.

**Comment by battlesnake** [comment]
For lack of any useful debugging information, closing

**Comment by marcinant** [comment]
Define what do you need to debug. System: ubuntu 15.10, npm 4.2 and 5.0, latest version of web-starter-kit
