### ISSUE TITLE
Support for http proxy

### ISSUE THREAD

**Issue by benningm** [battlesnake/gulp-google-webfonts#25]
The used 'http' class seems not to support a http proxy.
May be you can change the code to use 'request' instead since it does respect
http_proxy and https_proxy environment variables.

**Comment by battlesnake** [comment]
Good idea, PR would be appreciated

**Comment by rogersborchia** [comment]
I need this too! 👍

**Comment by battlesnake** [comment]
Submit a PR then :)

**Comment by benningm** [comment]
I found grunt-google-fonts and did an PR there:

https://github.com/Mika-/grunt-google-fonts/pull/7

**Comment by TomFoyster** [comment]
Why does a fix for the Grunt module warrant this issue being closed? It's still an issue with Gulp?

**Comment by battlesnake** [comment]
Nearly a year later, no PR for this issue - so I assumed it's a non-issue and closed it.
