### ISSUE TITLE
How to set path for fonts in generated CSS?

### ISSUE THREAD

**Issue by marko-stimac** [battlesnake/gulp-google-webfonts#33]
Is it possible define path in generated css/scss?
Currently it generates: 

`src: url(Open_Sans-normal-700.woff) format('woff');`

but I would like it to be this path 

`src: url(assets/fonts/lib/Open_Sans-normal-700.woff) format('woff');`

My folder structure is

```
assets/css
assets/fonts/fonts.list
assets/fonts/lib
```

```
gulp.task('fonts', function () {
	return gulp.src('./assets/fonts/fonts.list')
	.pipe(googleWebFonts({
		cssDir: '../../css/',
		fonts_dir: './lib',
		cssFilename: '_fonts.scss'
	}))
	.pipe(gulp.dest('assets/fonts/lib'));
});

```

**Comment by battlesnake** [comment]
Sounds similar to #20 or #7 (resolved in #9).  Please re-open if that is not the case.
