### ISSUE TITLE
woff2?

### ISSUE THREAD

**Issue by tmccarten** [battlesnake/gulp-google-webfonts#35]
It only downloads woff at present, is it possible to get the woff2?

**Comment by battlesnake** [comment]
There have been several issues raised about this, but so far no pull requests.  Closing as a duplicate, will re-open if a PR accompanies it.

**Comment by Nantris** [comment]
I can't imagine this is more than changing `woff` to `woff2` somewhere? Am I wrong? This looks like a great package, but it's pretty much useless in 2018 if it doesn't grab `woff2`

**Comment by Nantris** [comment]
For anyone from the future:

Pass this option: `format: 'woff2'`

**Comment by chriskrj** [comment]
can u pass more then 1 format?
