### ISSUE TITLE
version without gulp?

### ISSUE THREAD

**Issue by landsman** [battlesnake/gulp-google-webfonts#38]
Hi,

in first place - thank you for your package, it's awesome.
I have one question - feature request.

Do you think that should be possible create small nodejs package without dependency to gulp?
I have some project without gulp, just npm scripts, gulp could be there overkill.

**Comment by battlesnake** [comment]
It should be quite easy to extract the core from this module, such that you can inject into it a config and a function for emitting files/chunks.  With that, it should be possible to incorporate it into any build system and to use it standalone via CLI.  Happy to accept such a PR.
