### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by nterbogt** [battlesnake/gulp-google-webfonts#39]
Is it possible that we could have an option to use HTTPS for the fetching? Our internal network has issues fetching over HTTP but changing it in this version of the code would require a fork.

If you're happy, I can look at providing a PR with an option
```
  'protocol': 'https'
```
where the default would be http as it's currently implemented?

**Comment by battlesnake** [comment]
Happy to accept such a PR.  Also happy to accept one that makes HTTPS the default, if this doesn't break things.

**Comment by nterbogt** [comment]
Thanks. This has been added in #40.

**Comment by battlesnake** [comment]
Merged, thanks for contributing!
