### ISSUE TITLE
Support Material-Design-Icons?

### ISSUE THREAD

**Issue by ghost** [battlesnake/gulp-google-webfonts#4]
The material-design-icons have different css but it would be great if I could use it to download a local copy of roboto and material icons.

**Comment by battlesnake** [comment]
could you send me the URL to them, I'll update the CSS parser

**Comment by ghost** [comment]
https://www.google.com/design/icons/

it's hosted on google apis.

**Comment by battlesnake** [comment]
Hmm never heard of those before but they look really useful - are there any other webfonts that you know of which Google hosts, but which aren't on the "Google Webfonts" site?  If I have to add special branches for this font, maybe I can add some others too (Icomoon and FontAwesome might be candidates also)

**Comment by ghost** [comment]
No this is the only one that I know of.

**Comment by JosefJezek** [comment]
For icons is SVG format.

https://css-tricks.com/icon-fonts-vs-svg/

https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/app/elements/custom-icons/icons.html

**Comment by ghost** [comment]
..... No don't choose this. I want this plugin to download the webfont
version which is hosted on git and on Googleapis

**Comment by battlesnake** [comment]
What would you suggest?

I'm thinking that if Github font repos are often organised in similar ways, or the bower.json files get us around differences in organisation, we could have something like:

```
bower:github.com/owner/repo/bower.json
```

Then have the plugin curl that and resolve the font files from it (and also the font-family name), using that to curl those files as needed, then generate CSS.

I'd rather not add rules specifically for each popular webfont.

Suggestions?

**Comment by JosefJezek** [comment]
Good alternative source is http://openfontlibrary.org
