### ISSUE TITLE
Set site root as font url

### ISSUE THREAD

**Issue by onebitrocket** [battlesnake/gulp-google-webfonts#43]
How do you go about generating css output where the src url is prefixed with a `/`?

I'm trying to achieve a directory the following directory structure:

````
/
/fonts/fontfiles.woff
/css/fontcss.css
````
When loading in the css on any page that is not at site root I'm finding the font resource will fail to load.

````
@font-face {
	font-family: 'Oxygen';
	font-style: normal;
	font-weight: 700;
	font-display: auto;
	src: local('Oxygen Bold'), local('Oxygen-Bold'), url(fonts/Oxygen-normal-700.woff) format('woff');
	unicode-range: U+0-10FFFF;
}
````
**☝️ fails to load fonts on any page in a sub folder `/example/example-page.html`**

How do I configure this to output the font src in my css like this, whilst maintaining the above directory structure:

````
@font-face {
	font-family: 'Oxygen';
	font-style: normal;
	font-weight: 700;
	font-display: auto;
	src: local('Oxygen Bold'), local('Oxygen-Bold'), url(/fonts/Oxygen-normal-700.woff) format('woff');
	unicode-range: U+0-10FFFF;
}
````

Thanks

**Comment by battlesnake** [comment]
Happy to accept a PR that introduces this functionality, if it isn't already available with the `cssDir` / `fontsDir` options.
