### ISSUE TITLE
Attribute font-stretch doesn't match the regex

### ISSUE THREAD

**Issue by gabrielmdu** [battlesnake/gulp-google-webfonts#51]
Today I tried downloading the Cabin font and an error occurred. Upon investigation I discovered its font-face comes with the 
_font-stretch_ attribute which fails to match the formatting regex.

```
@font-face {
  font-family: 'Cabin';
  font-style: normal;
  font-weight: 400;
  font-stretch: normal;
  src: url(https://fonts.gstatic.com/s/cabin/v15/u-4X0qWljRw-PfU81xCKCpdpbgZJl6XFpfEd7eA9BIxxkV2EH7ilwQ.woff) format('woff');
}
```

**Comment by nterbogt** [comment]
This is causing us build issues also.
