### ISSUE TITLE
would be nice to pass a parameter to configure separate dir for fonts and css

### ISSUE THREAD

**Issue by caelcs** [battlesnake/gulp-google-webfonts#7]
for example if your project follow this structure 
/src
     | assets
                 | fonts
                 | css

I would expect to download the fonts in src/assets/fonts and css in src/assets/css, and the css will have the right url to access that font.

the gulp task would be like this:

gulp.task('fonts', function () {
    return gulp.src('./fonts.list')
        .pipe(googleWebFonts({fontDir: 'fonts', cssDir:'css'}))
        .pipe(gulp.dest('src/assets'));
});

**Comment by battlesnake** [comment]
Sure, send a pull request over

**Comment by astanciu** [comment]
:+1: 
This would help a lot in doing file path replacements for dev vs build tasks where in a build we may want the generated url()s to be elsewhere than in a dev/serve/watch setting

**Comment by battlesnake** [comment]
Merged, thanks!
